// Common Philippine banks + e-wallets, for the payout bank-name picker.
export const PH_BANKS = [
  'BDO Unibank',
  'BPI (Bank of the Philippine Islands)',
  'Metrobank',
  'Land Bank of the Philippines',
  'Philippine National Bank (PNB)',
  'UnionBank of the Philippines',
  'Security Bank',
  'China Bank',
  'RCBC',
  'EastWest Bank',
  'UCPB',
  'Development Bank of the Philippines (DBP)',
  'PSBank',
  'AUB (Asia United Bank)',
  'Robinsons Bank',
  'Maybank Philippines',
  'CIMB Bank Philippines',
  'ING Bank',
  'Tonik Bank',
  'Maya Bank',
  'SeaBank Philippines',
  'GoTyme Bank',
  'GCash',
  'Maya (PayMaya)',
]
