ALTER TABLE "Consultant" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "Consultant" ADD COLUMN IF NOT EXISTS "bankAccountNo" TEXT;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "bankName" TEXT;
ALTER TABLE "Employee" ADD COLUMN IF NOT EXISTS "bankAccountNo" TEXT;
